services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      icheTest:
        ipv4_address: 172.25.0.2
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234 
      - MONGO_INITDB_DATABASE=ossistant
    volumes:
      - ./server/database/mongodb/data:/data/db

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: client.Dockerfile
    restart: "on-failure"
    networks:
      icheTest:
        ipv4_address: 172.25.0.5
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment: 
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
      - case
  
  data:
    container_name: data
    build:
      context: ./server
      dockerfile: ./data/data.Dockerfile
    volumes:
      - ./server/data:/app
      - ./server/db_conn/mongo:/db_conn/mongo
      - ./server/db_conn/neo4j:/db_conn/neo4j
    networks:
      icheTest:
        ipv4_address: 172.25.0.6
    ports:
      - 5000:5000

networks:
  icheTest:
    name: icheTest
    driver: bridge
    ipam:
      config: 
        - subnet : 172.25.0.0/16